### ISSUE TITLE
有些资源链接已经失效了

### ISSUE THREAD

**Issue by balanceTWK** [plctlab/RISCV-Training#2]
Resources.md

**Comment by lazyparser** [comment]
感谢指出，后续我们来更新下。有些课程的资源可能会随着新学期的课程更新。

**Comment by shining1984** [comment]
经过测试，课程的第2和第3失效了，其他的一切正常。
回头找到合适的资源会更新。

**Comment by shining1984** [comment]
https://github.com/isrc-cas/RISCV-Training/pull/3/commits/29700b3fd67622a11aedd66609610a873c388bd3

已经在#3 PR中更新。

@lazyparser

**Comment by lazyparser** [comment]
good job
